### ISSUE TITLE
Update docs and add one setting

### ISSUE THREAD

**Issue by moridin1138** [darrent/nanoleaf-aurora-api#3]
Greetings!  Now that 1.5.0 is out the readme should reflect "v1" instead of "beta".

Also, I added this in my own fork, but perhaps you could add this setting to your library [(link)](https://github.com/moridin1138/nanoleaf-aurora-api/commit/8e9601911d6893d7f84bf9e5e2ff06e2df3d88bb)

**Comment by darrent** [comment]
I'll update the version but cannot add the additional setting at the moment as I'm unable to test it using the Aurora.  If you can test it would you mind submitting a pull request?
